flags: {}
image:
  containers:
  - base: fpco/ubuntu-with-libgmp:14.04
    name: 12wm
    entrypoints:
    - legendary-journey-exe
extra-package-dbs: []
packages:
- .
extra-deps:
- gps-1.2
resolver: lts-9.14
